version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
    - "8080:8080"
    environment:
    -  DB_SOURCE=postgresql://root:secret@postgres:5432/simple_bank?sslmode=disable
    depends_on:
      postgres:
        condition: service_healthy
        restart: true
  postgres:
    image: postgres:14-alpine
    environment:
    -  POSTGRES_USER=root
    -  POSTGRES_PASSWORD=secret
    -  POSTGRES_DB=simple_bank
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 10s
      timeout: 10s
      retries: 5
      start_period: 30s
